#!/usr/bin/env python3
"""Build a URDF file from geometry metadata produced by generate_geometry.py."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import xml.etree.ElementTree as ET


ASSET_DIR_NAME = "robot_assets"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--description",
        type=Path,
        default=Path(ASSET_DIR_NAME) / "robot_description.json",
        help="Geometry metadata JSON generated by generate_geometry.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(ASSET_DIR_NAME) / "generated_robot.urdf",
        help="Output URDF path.",
    )
    return parser.parse_args()


def format_xyz(values) -> str:
    return " ".join(f"{float(value):.9f}" for value in values)


def load_metadata(description_path: Path) -> dict:
    return json.loads(description_path.read_text(encoding="utf-8"))


def add_inertial(link_element: ET.Element, mass_properties: dict) -> None:
    inertial = ET.SubElement(link_element, "inertial")
    ET.SubElement(inertial, "origin", xyz=format_xyz(mass_properties["center_mass"]), rpy="0 0 0")
    ET.SubElement(inertial, "mass", value=f"{float(mass_properties['mass']):.9f}")
    inertia = mass_properties["inertia"]
    ET.SubElement(
        inertial,
        "inertia",
        ixx=f"{float(inertia[0][0]):.9f}",
        ixy=f"{float(inertia[0][1]):.9f}",
        ixz=f"{float(inertia[0][2]):.9f}",
        iyy=f"{float(inertia[1][1]):.9f}",
        iyz=f"{float(inertia[1][2]):.9f}",
        izz=f"{float(inertia[2][2]):.9f}",
    )


def add_mesh_geometry(parent: ET.Element, mesh_path: str, material_name: str, rgba: str) -> None:
    visual = ET.SubElement(parent, "visual")
    ET.SubElement(visual, "origin", xyz="0 0 0", rpy="0 0 0")
    geometry = ET.SubElement(visual, "geometry")
    ET.SubElement(geometry, "mesh", filename=mesh_path, scale="1 1 1")
    material = ET.SubElement(visual, "material", name=material_name)
    ET.SubElement(material, "color", rgba=rgba)

    collision = ET.SubElement(parent, "collision")
    ET.SubElement(collision, "origin", xyz="0 0 0", rpy="0 0 0")
    collision_geometry = ET.SubElement(collision, "geometry")
    ET.SubElement(collision_geometry, "mesh", filename=mesh_path, scale="1 1 1")


def color_for_role(role: str) -> tuple[str, str]:
    if role == "trunk":
        return "trunk_material", "0.35 0.35 0.38 1.0"
    if role == "upper_link":
        return "upper_link_material", "0.15 0.46 0.65 1.0"
    if role == "lower_link":
        return "lower_link_material", "0.11 0.60 0.44 1.0"
    if role == "foot":
        return "foot_material", "0.90 0.52 0.14 1.0"
    return "joint_material", "0.72 0.72 0.72 1.0"


def add_link(robot: ET.Element, link_data: dict) -> None:
    link_element = ET.SubElement(robot, "link", name=link_data["name"])
    add_inertial(link_element, link_data["mass_properties"])
    material_name, rgba = color_for_role(link_data["role"])
    add_mesh_geometry(link_element, link_data["mesh_path"], material_name, rgba)


def add_joint(robot: ET.Element, joint_data: dict) -> None:
    joint_element = ET.SubElement(robot, "joint", name=joint_data["name"], type=joint_data["type"])
    ET.SubElement(joint_element, "parent", link=joint_data["parent"])
    ET.SubElement(joint_element, "child", link=joint_data["child"])
    origin = joint_data["origin"]
    ET.SubElement(
        joint_element,
        "origin",
        xyz=format_xyz(origin["xyz"]),
        rpy=format_xyz(origin["rpy"]),
    )
    if joint_data["type"] != "fixed":
        ET.SubElement(joint_element, "axis", xyz=format_xyz(joint_data["axis"]))
        limit = joint_data["limit"]
        ET.SubElement(
            joint_element,
            "limit",
            lower=f"{float(limit['lower']):.9f}",
            upper=f"{float(limit['upper']):.9f}",
            effort=f"{float(limit['effort']):.9f}",
            velocity=f"{float(limit['velocity']):.9f}",
        )
        dynamics = joint_data.get("dynamics")
        if dynamics:
            ET.SubElement(
                joint_element,
                "dynamics",
                damping=f"{float(dynamics['damping']):.9f}",
                friction=f"{float(dynamics['friction']):.9f}",
            )


def build_urdf(metadata: dict, output_path: Path, description_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    robot = ET.Element("robot", name=metadata["robot_name"])

    for link_data in metadata["links"]:
        add_link(robot, link_data)

    for joint_data in metadata["joints"]:
        add_joint(robot, joint_data)

    tree = ET.ElementTree(robot)
    ET.indent(tree, space="  ")
    tree.write(output_path, encoding="utf-8", xml_declaration=True)

    metadata["urdf_path"] = output_path.relative_to(output_path.parent.parent if output_path.parent.parent.exists() else Path.cwd()).as_posix() if output_path.is_absolute() else output_path.as_posix()
    description_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    return output_path


def validate_static_stability_before_export(
    metadata: dict,
    threshold: float = 0.0,
) -> None:
    """Secondary CGPM/SSM safety check before writing the URDF file.

    The primary SSM gate runs inside generate_geometry.py before any STL
    file is written.  This function acts as a second line of defence when
    robot_description.json is edited manually or produced by an external
    tool that bypassed generate_geometry.py.

    Parameters
    ----------
    metadata  : dict   Loaded robot_description.json content.
    threshold : float  Minimum SSM in metres; default 0.0.

    Raises
    ------
    SystemExit  If SSM < threshold.
    """
    try:
        from stability import evaluate_ssm
    except ImportError as exc:
        print(f"[SSM] stability 模块导入失败，跳过静态稳定性检验: {exc}")
        return

    result = evaluate_ssm(metadata, threshold=threshold)
    ssm_val = result["ssm"]
    status = "PASS" if result["passed"] else "FAIL"
    print(f"[SSM] 重心投影法静态稳定裕度  SSM = {ssm_val:.4f} m  [{status}]")
    print(f"[SSM]   CoM XY          = {[round(v, 4) for v in result['com_xy']]}")
    print(f"[SSM]   支撑多边形顶点数  = {len(result['support_polygon_xy'])}")

    if not result["passed"]:
        raise SystemExit(
            f"\n[SSM] 静态稳定性检验不通过：SSM = {ssm_val:.4f} m < 阈值 {threshold} m。\n"
            "      质心投影在支撑多边形外，机器人设计需调整（调整腿分布或躯干几何）。\n"
            "      请重新运行 generate_geometry.py 后再生成 URDF。"
        )


def main() -> None:
    args = parse_args()
    metadata = load_metadata(args.description)
    validate_static_stability_before_export(metadata)
    output_path = build_urdf(metadata, args.output, args.description)
    print(f"URDF written to: {output_path}")


if __name__ == "__main__":
    main()