#!/usr/bin/env python3
"""Static test for the standard hexapod in PyBullet.

This script is modeled after test_sim.py, but targets the standard six-legged
robot generated by generate_standardurdf.py. It loads the standard URDF, puts
it into a standing posture, holds the pose under gravity, and reports static
stability metrics such as base roll/pitch, body height, and contact count.
"""

from __future__ import annotations

import argparse
import json
import math
import subprocess
import sys
import time
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pybullet as p
import pybullet_data


REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_DESC = REPO_ROOT / "robot_assets" / "standard_hexapod" / "robot_description.json"
DEFAULT_URDF = REPO_ROOT / "robot_assets" / "standard_hexapod" / "generated_robot.urdf"
GEN_SCRIPT = REPO_ROOT / "generate_standardurdf.py"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--urdf", type=Path, default=DEFAULT_URDF, help="Standard hexapod URDF path.")
    parser.add_argument("--description", type=Path, default=DEFAULT_DESC, help="Robot description JSON path.")
    parser.add_argument("--headless", action="store_true", help="Run without opening the GUI.")
    parser.add_argument("--steps", type=int, default=1200, help="Simulation steps to run.")
    parser.add_argument("--hold-steps", type=int, default=400, help="Initial stabilization steps.")
    parser.add_argument("--body-height", type=float, default=0.46, help="Initial base_link height above ground.")
    parser.add_argument("--stiffness", type=float, default=120.0, help="Global position-control stiffness.")
    parser.add_argument("--damping", type=float, default=6.0, help="Global position-control damping.")
    parser.add_argument("--effort", type=float, default=180.0, help="Per-joint effort cap.")
    parser.add_argument("--stance-lift-ratio", type=float, default=0.46,
                        help="Standing lift joint ratio. Around 0.46 keeps the femur near its design angle.")
    parser.add_argument("--stance-drop-ratio", type=float, default=0.08,
                        help="Standing drop joint ratio. Around 0.08 keeps the tibia naturally extended.")
    parser.add_argument("--swing-ratio", type=float, default=0.50, help="Neutral swing joint ratio.")
    parser.add_argument("--auto-generate", action="store_true",
                        help="Regenerate the standard URDF if it is missing.")
    return parser.parse_args()


def maybe_generate_standard_urdf(urdf_path: Path, description_path: Path) -> None:
    if urdf_path.exists() and description_path.exists():
        return
    if not GEN_SCRIPT.exists():
        raise FileNotFoundError(f"Missing generator: {GEN_SCRIPT}")
    print("[INFO] Standard URDF not found; generating it now...")
    subprocess.run([sys.executable, str(GEN_SCRIPT)], check=True)


def load_description(path: Path) -> Dict:
    return json.loads(path.read_text(encoding="utf-8"))


def quat_to_euler(w: float, x: float, y: float, z: float) -> Tuple[float, float, float]:
    sinr = 2.0 * (w * x + y * z)
    cosr = 1.0 - 2.0 * (x * x + y * y)
    roll = math.atan2(sinr, cosr)
    sinp = 2.0 * (w * y - z * x)
    pitch = math.asin(max(-1.0, min(1.0, sinp)))
    siny = 2.0 * (w * z + x * y)
    cosy = 1.0 - 2.0 * (y * y + z * z)
    yaw = math.atan2(siny, cosy)
    return roll, pitch, yaw


def get_base_pose(robot_id: int) -> Tuple[Tuple[float, float, float], Tuple[float, float, float]]:
    pos, orn = p.getBasePositionAndOrientation(robot_id)
    roll, pitch, yaw = quat_to_euler(orn[0], orn[1], orn[2], orn[3])
    return (float(pos[0]), float(pos[1]), float(pos[2])), (roll, pitch, yaw)


def set_robot_alpha_preserve_rgb(robot_id: int, alpha: float) -> None:
    visual_data = p.getVisualShapeData(robot_id)
    if not visual_data:
        return
    for item in visual_data:
        link_index = int(item[1])
        rgba = item[7]
        if rgba is None or len(rgba) < 3:
            continue
        color = [float(rgba[0]), float(rgba[1]), float(rgba[2]), float(alpha)]
        p.changeVisualShape(robot_id, link_index, rgbaColor=color)


def build_joint_target_map(
    robot_id: int,
    stance_lift_ratio: float,
    stance_drop_ratio: float,
    swing_ratio: float,
) -> Dict[int, float]:
    joint_targets: Dict[int, float] = {}
    num_joints = p.getNumJoints(robot_id)
    for joint_index in range(num_joints):
        info = p.getJointInfo(robot_id, joint_index)
        name = info[1].decode("utf-8")
        lower = float(info[8]) if math.isfinite(info[8]) else -0.5
        upper = float(info[9]) if math.isfinite(info[9]) else 0.5
        if upper <= lower:
            target = 0.0
        elif "_lift" in name:
            target = lower + np.clip(stance_lift_ratio, 0.0, 1.0) * (upper - lower)
        elif "_drop" in name:
            target = lower + np.clip(stance_drop_ratio, 0.0, 1.0) * (upper - lower)
        elif "_swing" in name:
            target = lower + np.clip(swing_ratio, 0.0, 1.0) * (upper - lower)
        else:
            target = 0.5 * (lower + upper)
        joint_targets[joint_index] = float(target)
    return joint_targets


def apply_joint_targets(robot_id: int, joint_targets: Dict[int, float], stiffness: float,
                        damping: float, effort: float) -> None:
    num_joints = p.getNumJoints(robot_id)
    position_gain = float(np.clip(stiffness / 1500.0, 0.02, 0.25))
    velocity_gain = float(np.clip(damping / 20.0, 0.05, 1.0))
    for joint_index in range(num_joints):
        target = joint_targets.get(joint_index, 0.0)
        p.setJointMotorControl2(
            bodyIndex=robot_id,
            jointIndex=joint_index,
            controlMode=p.POSITION_CONTROL,
            targetPosition=target,
            positionGain=position_gain,
            velocityGain=velocity_gain,
            force=effort,
        )


def joint_name_map(robot_id: int) -> Dict[str, int]:
    mapping: Dict[str, int] = {}
    for joint_index in range(p.getNumJoints(robot_id)):
        name = p.getJointInfo(robot_id, joint_index)[1].decode("utf-8")
        mapping[name] = joint_index
    return mapping


def main() -> int:
    args = parse_args()

    if args.auto_generate:
        maybe_generate_standard_urdf(args.urdf, args.description)

    if not args.urdf.exists():
        print(f"[ERROR] URDF not found: {args.urdf}")
        print("[INFO] Run generate_standardurdf.py first, or pass --auto-generate.")
        return 1

    if not args.description.exists():
        print(f"[ERROR] Description not found: {args.description}")
        print("[INFO] Run generate_standardurdf.py first, or pass --auto-generate.")
        return 1

    description = load_description(args.description)
    try:
        from stability import evaluate_ssm
        ssm_result = evaluate_ssm(description, threshold=0.0)
        print("[SSM] Static stability analysis")
        print(f"  com_xy   = {ssm_result['com_xy']}")
        print(f"  ssm      = {ssm_result['ssm']:.4f} m")
        print(f"  passed   = {ssm_result['passed']}")
    except Exception as exc:
        print(f"[WARN] Could not evaluate SSM: {exc}")

    client = p.connect(p.DIRECT if args.headless else p.GUI)
    if client < 0:
        print("[ERROR] Failed to start PyBullet.")
        return 1

    p.setAdditionalSearchPath(pybullet_data.getDataPath())
    p.setGravity(0, 0, -9.81)
    p.setTimeStep(1.0 / 240.0)
    p.loadURDF("plane.urdf")

    start_pos = (0.0, 0.0, float(args.body_height))
    start_orn = p.getQuaternionFromEuler((0.0, 0.0, 0.0))
    robot_id = p.loadURDF(str(args.urdf), start_pos, start_orn, useFixedBase=False)
    if robot_id < 0:
        print(f"[ERROR] Failed to load URDF: {args.urdf}")
        return 1

    joint_targets = build_joint_target_map(
        robot_id,
        stance_lift_ratio=args.stance_lift_ratio,
        stance_drop_ratio=args.stance_drop_ratio,
        swing_ratio=args.swing_ratio,
    )
    apply_joint_targets(robot_id, joint_targets, args.stiffness, args.damping, args.effort)

    joint_map = joint_name_map(robot_id)
    print(f"[OK] Loaded standard hexapod with {p.getNumJoints(robot_id)} joints")
    print(f"[OK] Initial base pose: {start_pos}")
    print("[OK] Standing joint ratios:")
    print(f"  stance_lift_ratio = {args.stance_lift_ratio:.3f}")
    print(f"  stance_drop_ratio = {args.stance_drop_ratio:.3f}")
    print(f"  swing_ratio       = {args.swing_ratio:.3f}")
    print("[OK] Joint name map:")
    for name, idx in sorted(joint_map.items(), key=lambda item: item[1]):
        print(f"  [{idx:2d}] {name}")

    if not args.headless:
        p.resetDebugVisualizerCamera(
            cameraDistance=2.8,
            cameraYaw=35.0,
            cameraPitch=-22.0,
            cameraTargetPosition=[0.0, 0.0, 0.25],
        )

    roll_samples: List[float] = []
    pitch_samples: List[float] = []
    base_z_samples: List[float] = []
    contact_samples: List[int] = []

    print(f"[HOLD] Stabilizing for {args.hold_steps} steps ...")
    for step in range(max(args.steps, 1)):
        apply_joint_targets(robot_id, joint_targets, args.stiffness, args.damping, args.effort)
        p.stepSimulation()

        base_pos, (roll, pitch, yaw) = get_base_pose(robot_id)
        contacts = p.getContactPoints(bodyA=robot_id)
        contact_samples.append(len(contacts))

        if step >= max(args.hold_steps, 0):
            roll_samples.append(roll)
            pitch_samples.append(pitch)
            base_z_samples.append(base_pos[2])

        if (step + 1) % 120 == 0:
            print(
                f"[{step + 1:4d}/{args.steps}] "
                f"z={base_pos[2]:.4f} m  "
                f"roll={math.degrees(roll):+.2f}°  "
                f"pitch={math.degrees(pitch):+.2f}°  "
                f"contacts={len(contacts)}"
            )

        if not args.headless:
            time.sleep(1.0 / 240.0)

    if roll_samples:
        roll_arr = np.asarray(roll_samples, dtype=float)
        pitch_arr = np.asarray(pitch_samples, dtype=float)
        z_arr = np.asarray(base_z_samples, dtype=float)
        print("\n[Summary] Static posture metrics")
        print(f"  roll_mean  = {math.degrees(float(np.mean(roll_arr))):+.3f}°")
        print(f"  roll_std   = {math.degrees(float(np.std(roll_arr))):.3f}°")
        print(f"  pitch_mean = {math.degrees(float(np.mean(pitch_arr))):+.3f}°")
        print(f"  pitch_std  = {math.degrees(float(np.std(pitch_arr))):.3f}°")
        print(f"  body_z_mean = {float(np.mean(z_arr)):.4f} m")
        print(f"  body_z_std  = {float(np.std(z_arr)):.6f} m")
        print(f"  avg_contacts = {float(np.mean(contact_samples)):.2f}")

    if not args.headless:
        print("[WAIT] GUI mode stays open. Press Q / ESC or close the window to exit.")
        while p.isConnected():
            keys = p.getKeyboardEvents()
            if (
                (ord("q") in keys and keys[ord("q")] & p.KEY_WAS_TRIGGERED)
                or (ord("Q") in keys and keys[ord("Q")] & p.KEY_WAS_TRIGGERED)
                or (p.B3G_ESCAPE in keys and keys[p.B3G_ESCAPE] & p.KEY_WAS_TRIGGERED)
            ):
                break
            time.sleep(0.05)

    print("[OK] Static test finished.")
    p.disconnect()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
