"""Kinematic helpers for morphology-independent stance adaptation."""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Sequence

import numpy as np


def compensated_stance_ik(
    urdf_path: Path,
    compensation_xy: Sequence[float],
    body_height: float = 0.50,
    compensation_scale: float = 0.75,
    max_iterations: int = 40,
) -> Dict[str, float]:
    """Return joint targets that move the chassis toward the support centre.

    With the chassis fixed, translating all contacts by ``-t`` is equivalent to
    translating the chassis by ``t`` over fixed contacts.  A damped numerical
    Jacobian handles the arbitrary branched URDFs generated by this project.
    """
    import pybullet as pb

    translation = np.asarray(compensation_xy[:2], dtype=float) * compensation_scale
    if float(np.linalg.norm(translation)) < 1e-5:
        return {}
    client = pb.connect(pb.DIRECT)
    try:
        robot = pb.loadURDF(str(Path(urdf_path).resolve()), [0, 0, body_height], useFixedBase=True)
        movable, names, lower, upper, feet = [], [], [], [], []
        for idx in range(pb.getNumJoints(robot)):
            info = pb.getJointInfo(robot, idx)
            if info[2] != pb.JOINT_FIXED:
                movable.append(idx)
                names.append(info[1].decode())
                lower.append(float(info[8]))
                upper.append(float(info[9]))
            if info[12].decode().endswith("_foot"):
                feet.append(idx)
        if not movable or not feet:
            return {}

        q = np.zeros(len(movable), dtype=float)
        lo, hi = np.asarray(lower), np.asarray(upper)

        def set_q(values):
            for column, joint in enumerate(movable):
                pb.resetJointState(robot, joint, float(values[column]))

        def positions():
            return np.concatenate([
                np.asarray(pb.getLinkState(robot, foot, computeForwardKinematics=True)[0])
                for foot in feet
            ])

        set_q(q)
        target = positions().reshape(-1, 3)
        target[:, :2] -= translation
        target[:, 2] = 0.0
        target = target.ravel()
        eps = 1e-4
        for _ in range(max_iterations):
            set_q(q)
            current = positions()
            error = target - current
            if float(np.linalg.norm(error)) < 0.015:
                break
            jacobian = np.zeros((len(current), len(q)))
            for column in range(len(q)):
                perturbed = q.copy()
                perturbed[column] += eps
                set_q(perturbed)
                jacobian[:, column] = (positions() - current) / eps
            normal = jacobian @ jacobian.T + 1e-3 * np.eye(len(current))
            q = np.clip(q + 0.5 * jacobian.T @ np.linalg.solve(normal, error), lo, hi)
        return dict(zip(names, map(float, q)))
    finally:
        pb.disconnect(client)
